### PR TITLE
updated and new config params

### PR DESCRIPTION
**Pull request by saelbrec**

### CODE REVIEW

**Comment by redlicha** [comment]
https://github.com/openvstorage/volumedriver/commit/dc48f202b258045bc5e1d6201a73800838bc0c90 introduces `--config-help` and `--config-help-markdown` command line options to the volumedriver_fs binary, obviating the need to manually update `config.md`.

Do we even want to keep that file around any longer as there's still the potential of it getting out of sync?

**Comment by saelbrec** [comment]
If --config-help does the job than config.md shouldn't be more than a pointer to that. In other words, unless @wimpers has objections to keep it around for some reason I think you can update it as part of this PR.

**Comment by wimpers** [comment]
Can't we make something so as part of the release script the output of --config-help-markdown gets commited to docs/config.md

I would like to keep a browsable/searchable version in the documentation.

**Comment by redlicha** [comment]
@wimpers: such a script will still have to be created (voldrv releases are currently driven by the git-flow tools which are used unmodified) - https://github.com/openvstorage/volumedriver/issues/155

**Comment by redlicha** [comment]
Closing this one without merging - the documentation will be updated on release with `--config-help-markdown`.

**Pull request closed without merging**
